spring:
  application:
    name: provider-service #应用/微服务名字
  cloud:
    nacos:
      discovery:
        server-addr: 49.234.82.226:8848 #nacos服务器地址
        username: nacos #用户名密码
        password: nacos

server:
  port: 8081
